title: London Infosec
description: A group of London academics (& friends) working on Infosec.
show_downloads: true
theme: jekyll-theme-dinky
logo: /assets/red-logo.jpg
url: https://london-infosec.github.io/
author: London Infosec
plugins:
  - jekyll-seo-tag
